version: '3.0'

services:
  action_server:
    image: action_end:latest
    ports:
      - 5055:5055
    volumes:
      - ./actions:/app/actions
  rasa_nlu:
    image: rasa/rasa_nlu:0.13.8-spacy
    ports:
      - 5000:5000
    volumes:
      - ./models/rasa_nlu:/app/models
    command:
      - start
      - --path
      - models
